### ISSUE TITLE
actget should allow setting output folder

### ISSUE THREAD

**Issue by ntadej** [ARCControlTower/aCT#83]
Another simple one for @jakobmerljak:

`actget` currently downloads files in the working directory. For scripting purposes it would be useful to also support overriding the working directory.

For example
```
actget -a -f MY_JOB_NAME -o /output
```
would result in a folder `/output/MY_JOB_NAME`.

**Comment by jakobmerljak** [comment]
Implemented in #84. `-D`/`--dir` parameter is used to be consistent with ARC client's interface.
