### ISSUE TITLE
Proxies overwritten by daemon in multi-user setup

### ISSUE THREAD

**Issue by ntadej** [ARCControlTower/aCT#92]
We are running aCT client where one user (e.g. `a`) runs the daemon and multiple users submit jobs with independent proxies.
There are then for example two proxy files in `run` folder:
 - `proxiesid1` (owned by user `a`)
 - `proxiesid2` (owned by user `b`)

What is happening is that other users' proxies are periodically overwritten and change ownership to user `a`. Interestingly this does not happen to that user's proxy (file `proxiesid1` has not changed for a few days).

User `b` now can not submit jobs as proxy permissions are `600`. Because of that this file `proxiesid2` can also not be overwritten.

**Comment by jakobmerljak** [comment]
Yes, there are known issues with proxy certificate ownership on multi user setups used with local aCT client. This seems to be another one. Local aCT client has not been updated with recent development and might require some redesign to solve local multi user problems. For now, it should not be considered for use.

Instead, the client for aCT REST setups [could be considered](https://github.com/ARCControlTower/aCT/tree/master/src/act/client/aCT-client).
